dist: trusty
sudo: required
language: go
go:
- 1.9.x
before_install:
- sudo curl https://glide.sh/get | sh
script:
- "./update.sh"
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push lmacko1992
env:
  global:
     - secure: VentZ33Ibnm6Oes1ndwfiFPA4gBfo0NeqyQDc4UESSSVGVcm6bCzcVAia11tiExHL62dgmWh0vTMk5a8WAOlqTtX/yb1pfqXaRkKcMH9nmROi38bmJLoWWCXJoZqdQyU2v7k2SvkvCg637F+SFLAMMc5x1sQvo/Q8e25o8YDOWflECb4AtvUDW1r1S65isITz7P98AgLXRgQJQ5hBneWfyBTIiqpdz5y4pacQuumyQxTX+dlWyqIeap7jeae0UyqDPOknJnS8Gk1pn3DHzZQe/ggjUf9nuj1YPZwAXC3uBbzsXayGAg6i8n/yMRTh3dCReTkpe8xj6t9qC5WnXMi/r1stveWK3X5ErCSk8E9M6LpFSzUGSE6r8Guuqny6EHd4IzlMNg+5cmMRYa2SuolQ6iFc2Lh1pbt0sImvEKtIFU/vEnFUtL43VNjwPdYzByNJJCMd3vZOZlzampA3UUVM0PLyKIYkVaY/Wlgnhxb2V8HDqH6elvYaIvxP7vd711gA+jmn3Uygtlpmcoh88TW3TuAIZUZ4jVdNlEwXT2cWXLkZ9Z+NaZ1hMZsh4RhSsV66Jl9YGeh4OpbYbA6EbmHyMAu86+yBMCMZsd9KGIdy3yOt5HeBn0x4peNmopm+zKpn+i0sVvm1Ns/vxZ1oNQB5SQMI1gF7+58t5fAjx3+aeg=
     - secure: sZ8xYiQYJh9YTeDqG3qQIJYLSGK7WVDPmZ4Z/AyiQxNCWo8gdiZCKYW8uZXI3unHlhU71FgcBwGwjrRgjY3/opazTUpCFc92yPRyDbrVIPtwpPwuMHyhTWXgj0nF93fQkJpsqe+u068Ify9/GiARGEnsjWXOJ2A4tan8DUljpYpaRMfUd+NC6f1llZzBx+62JtE8AshYPsDb6Xm+LX16/0de47ZkcwaStDWglrHyV7UmyfiROTQ7+/YTYYzKeW4WMM48Qw4JwUbtw9RPa2H5Pr0KOeH2IEF80LOcVa1zCZbNJMPao6ujSJHRh1yCdZJE4btLAHrlnaRsNLuwtp0q3qgE43oTmVf8kZMxtxifnH59x/z/7eAxw1PTnH5b6Gv611uRdc2XFjy8ZiT+83wcFWq98tVIrzYYsegG/qxGS4yGQEeqlsizjr7yU8X1nZFRz40TA31LdQnw0fBMDfs9MbioVzIbAcsmxTPWOazQwLsuGEok3w93N7YiWS3gJA6gWG1Mw3uLmGSticJsOOFJv5Ulj5eYBIw/E7vqcL28t7z4UjK4NcuEbeSB3YbYYyey5oNakyTpJ72u13NFanzQ5wi0CYKI29Is+iD21l1z26qAmjKrFxCz4xIoEpLgc8xUYqmgzlZq+KYMzLj4HoiJebq9aPbbcq7J8OfWqItdpA4=


